### ISSUE TITLE
创建一个cube的时候，代码直接报错

### ISSUE THREAD

**Issue by MUZLATAN** [amcax-kernel/amcax-daemon#2]
创建一个cube的时候，代码直接报错
![image](https://github.com/amcax-kernel/amcax-daemon/assets/37372290/7f713d7d-0626-4cfa-996e-a8611b3b5bb2)
需要如何解决
代码结构如下：
![image](https://github.com/amcax-kernel/amcax-daemon/assets/37372290/99d5e6c5-0c90-4cf8-baf2-7a0babd609e7)
![image](https://github.com/amcax-kernel/amcax-daemon/assets/37372290/ab68d50e-f311-4675-af07-51f096dbaf44)
![image](https://github.com/amcax-kernel/amcax-daemon/assets/37372290/92191349-2973-41f2-bfa5-44f4f1ea7809)

运行界面：
![image](https://github.com/amcax-kernel/amcax-daemon/assets/37372290/9fef785e-0452-4742-8f2f-ecdf610bfc37)

**Comment by ray-amcax** [comment]
请尝试一下构建Release版本的精灵，您所拿到的内核库很可能是release版本的，目前debug版的应用还不能使用release版本的内核库。

**Comment by MUZLATAN** [comment]
![20231130124438_rec_](https://github.com/amcax-kernel/amcax-daemon/assets/37372290/df6e34fc-0ac7-48cf-8e3b-ff6b15989488)
使用的release 版本， 点了按钮没反应，也没出现几何体

**Comment by ray-amcax** [comment]
您好，如果方便的话，请从官网上添加我们客服微信，以便技术支持能联系您了解更多情况。

**Comment by ray-amcax** [comment]
@MUZLATAN 您好，如果问题还在并且需要解决的话，请在30天内通过官网联系我们客服，没有更多信息的话，30天内我们将关闭此issue.
