### ISSUE TITLE
代码为什么涉及到RPC服务器，是否有后门?

### ISSUE THREAD

**Issue by lavender-lee** [amcax-kernel/amcax-daemon#4]
```txt
0x00007FFEC66FCF19 (KernelBase.dll)处(位于 AmcaxDaemon.exe 中)引发的异常: 0x000006BA: RPC 服务器不可用。。

```

![image](https://github.com/amcax-kernel/amcax-daemon/assets/35004095/df2b9488-768b-46aa-974f-3c8b5fa9da60)

**Comment by ray-amcax** [comment]
您好，请参考https://blog.csdn.net/u010963948/article/details/78525490。简单来说RPC服务可能是任何软件模块，Windows系统中很多COM组件都以RPC的方式给客户软件提供调用接口，包括文件对话框等（请参看这篇文章https://blog.csdn.net/dxy408460910/article/details/44060927）。因此，RPC的存在并不意味着程序在开后门，请知悉。
